VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
LTO_ENABLE = no

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
OLED_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

SRC += oneshot.c
SRC += bongo_cat.c
